In [3]:
import torch

In [23]:
x =  torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x.shape

torch.Size([10])

In [13]:
X = x.reshape(2,5)
X

tensor([[0, 1]])

In [29]:
torch.ones((2,3,4))
torch.zeros(2,3,4).shape

torch.Size([2, 3, 4])

In [24]:
torch.tensor([[2,1,1,3],[1,2,3,3]])

torch.Size([2, 4])

In [39]:
x = torch.tensor([1.0,2,3,4,5])
y = torch.ones(5)
x,y,x+y,x*y,x**y,x**x

(tensor([1., 2., 3., 4., 5.]),
 tensor([1., 1., 1., 1., 1.]),
 tensor([2., 3., 4., 5., 6.]),
 tensor([1., 2., 3., 4., 5.]),
 tensor([1., 2., 3., 4., 5.]),
 tensor([1.0000e+00, 4.0000e+00, 2.7000e+01, 2.5600e+02, 3.1250e+03]))

In [48]:
x =torch.arange(12,dtype=torch.float32).reshape(3,4)
y =torch.tensor([[2.,1,3,3],[1,2,3,4],[1,2,3,4]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1),x


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [49]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
x.sum() 

tensor(66.)

boardcast

In [52]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [53]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [63]:
x[1],x[-1],x[:5] #多余的还是取全部

(tensor([4., 5., 6., 7.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [66]:
x[0,1] =10
x

tensor([[ 0., 10.,  2.,  3.],
        [ 4., 10.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [68]:
x[0::2,:] = 6
x

tensor([[6., 6., 6., 6.],
        [4., 4., 4., 4.],
        [6., 6., 6., 6.]])

关于内存

In [76]:
before = id(y)
y = x+y
#y += x  # true
id(y) == before

False

In [79]:
z = torch.zeros_like(y)
z1 = torch.zeros_like(y)
print("id(z):",id(z))
z =x + y
print("id(z)",id(z))


id(z): 2736077943968
id(z) 2736077942192


比较大的注意不要过多赋值

In [80]:
A = X.numpy()
B =torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [81]:
a =torch.tensor([45.5])
a,a.item(),float(a),int(a)  #numpy

(tensor([45.5000]), 45.5, 45.5, 45)