In [19]:
import torch
import torch.nn as nn
from d2l import torch as d2l
%matplotlib inline

In [ ]:
def pool2d(X,pool_size,mode='max'):
   p_h,p_w = pool_size
   Y = torch.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
   for i in range(Y.shape[0]):
      for j  in range(Y.shape[1]):
         if mode == 'max':
            Y [i,j] = X [i:i+p_h,j:j+p_w].max()
         if mode == 'avg ':
            Y[i,j] = X [i,i+p_h,j:j+p_w].mean()
   return Y

In [11]:
X = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [9]:
Z = torch.arange(32,dtype=torch.float32).reshape((2,4,2,2))
Z

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]],

         [[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]]],


        [[[16., 17.],
          [18., 19.]],

         [[20., 21.],
          [22., 23.]],

         [[24., 25.],
          [26., 27.]],

         [[28., 29.],
          [30., 31.]]]])

In [12]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

pytorch默认使用步幅和池化窗口形状相同
所以看到的是10

In [13]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [15]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [16]:
X = torch.cat((X,X+1),dim=1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [17]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])