计算图
反向传递的英文


中间值存储耗费资源

In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)  #x= torch.arange(4,requires_grad=True)
x.grad  #none init

In [4]:
y = 2 * torch.dot(x,x)  #下面是  隐式构造  有一个计算梯度的函数
y 

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

会一直保存grad  要清零

In [14]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y = x * x
y.sum().backward()   #对于向量的梯度 先求和
x.grad

tensor([0., 2., 4., 6.])

move out of the culculation pic
can static your parameter

In [19]:
x.grad.zero_()
y = x * x
u = y.detach()  #move  
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])